<a href="https://colab.research.google.com/github/natalia1126solomon/Shoreline-Hazards-and-Habitats/blob/main/Shoreline-Hazards-and-Habitats/ingestion%20/notebooks/FinalProjectCleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

I began cleaning my data by viewing the column names after reading the data.

In [ ]:
import pandas as pd
import json
from google.colab import files

In [1]:
uploaded = files.upload()

Saving Maryland_Coastal_Resiliency_Assessment_-_Shoreline_Hazard_Index.csv to Maryland_Coastal_Resiliency_Assessment_-_Shoreline_Hazard_Index.csv

In [2]:
md = pd.read_csv("Maryland_Coastal_Resiliency_Assessment_-_Shoreline_Hazard_Index.csv")
md.head()

,OBJECTID,x,y,Sheltered_Coastline,Geomorphology_Hazard,Elevation_Hazard,Sea_Level_Rise_Hazard,Wave_Hazard,storm_surge_hazard,Erosion_Rate_Hazard,...,Community_Flood_Risk_Max,Community_Flood_Risk_Nearest,Shoreline_Priority_Area,County,EI_wHAB,EI_woHAB,hab_role,NearRiskD,Latitude,Longitude
0,1,401798.774493,4.385197e+06,Yes,Very High,Very Low,Low,Very Low,Very Low,Low,...,Low,Low,NaN,Harford,1.93070,1.93070,0.000000,1705.315430,39.610466,-76.143656
1,2,402048.774493,4.385197e+06,Yes,Very High,Very Low,Low,Low,Very Low,Low,...,Low,Low,NaN,Harford,2.13166,2.13166,0.000000,1485.031860,39.610406,-76.141068
2,3,402298.774493,4.385197e+06,Yes,Very High,Very Low,Low,Very Low,Very Low,Low,...,Moderate,Low,NaN,Harford,1.93070,1.93070,0.000000,1238.374023,39.610339,-76.138159
3,4,402798.774493,4.385197e+06,Yes,High,Very Low,Low,Low,Very Low,Low,...,Moderate,Low,NaN,Harford,2.06478,2.06478,0.000000,746.736511,39.610230,-76.132298
4,5,403048.774493,4.385197e+06,Yes,Very High,Very Low,Low,Low,Very Low,Low,...,Moderate,Low,Tier 2,Harford,1.84218,2.13166,0.289478,507.528381,39.610262,-76.129386

In [3]:
md

,OBJECTID,x,y,Sheltered_Coastline,Geomorphology_Hazard,Elevation_Hazard,Sea_Level_Rise_Hazard,Wave_Hazard,storm_surge_hazard,Erosion_Rate_Hazard,...,Community_Flood_Risk_Max,Community_Flood_Risk_Nearest,Shoreline_Priority_Area,County,EI_wHAB,EI_woHAB,hab_role,NearRiskD,Latitude,Longitude
0,1,401798.774493,4.385197e+06,Yes,Very High,Very Low,Low,Very Low,Very Low,Low,...,Low,Low,NaN,Harford,1.93070,1.93070,0.000000,1705.315430,39.610466,-76.143656
1,2,402048.774493,4.385197e+06,Yes,Very High,Very Low,Low,Low,Very Low,Low,...,Low,Low,NaN,Harford,2.13166,2.13166,0.000000,1485.031860,39.610406,-76.141068
2,3,402298.774493,4.385197e+06,Yes,Very High,Very Low,Low,Very Low,Very Low,Low,...,Moderate,Low,NaN,Harford,1.93070,1.93070,0.000000,1238.374023,39.610339,-76.138159
3,4,402798.774493,4.385197e+06,Yes,High,Very Low,Low,Low,Very Low,Low,...,Moderate,Low,NaN,Harford,2.06478,2.06478,0.000000,746.736511,39.610230,-76.132298
4,5,403048.774493,4.385197e+06,Yes,Very High,Very Low,Low,Low,Very Low,Low,...,Moderate,Low,Tier 2,Harford,1.84218,2.13166,0.289478,507.528381,39.610262,-76.129386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14323,14324,423798.774493,4.196947e+06,No,Very High,Very High,Very High,High,Moderate,Very Low,...,NaN,NaN,NaN,Somerset,3.24688,3.57750,0.330622,4767.392578,37.917749,-75.866368
14324,14325,424048.774493,4.196947e+06,No,Very High,Very High,Very High,High,Moderate,Very Low,...,NaN,NaN,NaN,Somerset,3.24688,3.57750,0.330622,4736.051758,37.917633,-75.865274
14325,14326,421798.774493,4.196697e+06,No,Very High,Very High,Very High,High,Moderate,Low,...,NaN,NaN,NaN,Somerset,3.57650,3.94989,0.373381,5919.354980,37.914928,-75.888566
14326,14327,422298.774493,4.196697e+06,No,Very High,Very High,Very High,High,Moderate,Low,...,NaN,NaN,NaN,Somerset,3.57650,3.94989,0.373381,5846.572754,37.914429,-75.883710
14327,14328,422548.774493,4.196697e+06,No,Very High,Very High,Very High,High,Moderate,Low,...,NaN,NaN,NaN,Somerset,3.57650,3.94989,0.373381,5765.888672,37.914515,-75.881195

In [4]:
uploaded = files.upload()

Saving marsh_data.json to marsh_data.json

In [5]:
with open("marsh_data.json", "r") as f:
    data = json.load(f)


marsh_data = pd.DataFrame([feature['attributes'] for feature in data['features']])

marsh_data.to_csv("marsh_data.csv", index=False)

In [6]:
md.shape

(14328, 28)

In [7]:
md.columns

Index(['OBJECTID', 'x', 'y', 'Sheltered_Coastline', 'Geomorphology_Hazard',
       'Elevation_Hazard', 'Sea_Level_Rise_Hazard', 'Wave_Hazard',
       'storm_surge_hazard', 'Erosion_Rate_Hazard', 'Forest_Present',
       'Marsh_Present', 'Dune_Present', 'Oyster_Reef_Present',
       'Underwater_Grass_Present', 'Hazard_with_Habitats',
       'Hazard_without_Habitats', 'Hazard_Reduction_by_Habitats',
       'Community_Flood_Risk_Max', 'Community_Flood_Risk_Nearest',
       'Shoreline_Priority_Area', 'County', 'EI_wHAB', 'EI_woHAB', 'hab_role',
       'NearRiskD', 'Latitude', 'Longitude'],
      dtype='object')

My code below merges my two datasets using OBJECTID so all information is combined into one dataframe called merged. It then cleans and standardizes the data by converting habitat presence columns from “Yes/No” into numeric values "0/1". Next, it converts several hazard-related columns from categorical labels like “Low” or “High” into numeric scores 0–4 so they can be used in statistical analysis. Finally, I made sure the main hazard variables were treated as ordered categories.

In [25]:
#used built in Gemini

habitats = [
    "Forest_Present",
    "Marsh_Present",
    "Dune_Present",
    "Oyster_Reef_Present",
    "Underwater_Grass_Present"
]
hazard_mapping = {
    'Very Low': 0,
    'Low': 1,
    'Moderate': 2,
    'High': 3,
    'Very High': 4
}
hazard_order = ["Very Low", "Low", "Moderate", "High", "Very High"]
hazard_cols = [
    'Geomorphology_Hazard', 'Elevation_Hazard',
    'Sea_Level_Rise_Hazard', 'Wave_Hazard',
    'storm_surge_hazard', 'Erosion_Rate_Hazard'
]


merged = pd.merge(md, marsh_data, on='OBJECTID', how='left')


for h in habitats:
    if h in merged.columns:

        merged.loc[:, h] = merged[h].map({"Yes": 1, "No": 0}).fillna(0).astype(int)


if 'Hazard_Reduction_by_Habitats' in merged.columns:
    merged.loc[:, 'Hazard_Reduction_by_Habitats_Numeric'] = merged['Hazard_Reduction_by_Habitats'].map(hazard_mapping)
if 'Hazard_with_Habitats' in merged.columns:
    merged.loc[:, 'Hazard_with_Habitats_Numeric'] = merged['Hazard_with_Habitats'].map(hazard_mapping)
if 'Hazard_without_Habitats' in merged.columns:
    merged.loc[:, 'Hazard_without_Habitats_Numeric'] = merged['Hazard_without_Habitats'].map(hazard_mapping)


if 'Community_Flood_Risk_Max' in merged.columns:
    merged.loc[:, 'Community_Flood_Risk_Max_Numeric'] = merged['Community_Flood_Risk_Max'].map(hazard_mapping)


for col in hazard_cols:
    if col in merged.columns:
        merged.loc[:, col] = pd.Categorical(merged[col], categories=hazard_order, ordered=True)

In [9]:
merged

,OBJECTID,x,y,Sheltered_Coastline,Geomorphology_Hazard,Elevation_Hazard,Sea_Level_Rise_Hazard,Wave_Hazard,storm_surge_hazard,Erosion_Rate_Hazard,...,Probability,HazScore,TotalScore,Overall_Rating,Shape__Area,Shape__Length,Hazard_Reduction_by_Habitats_Numeric,Hazard_with_Habitats_Numeric,Hazard_without_Habitats_Numeric,Community_Flood_Risk_Max_Numeric
0,1,401798.774493,4.385197e+06,Yes,Very High,Very Low,Low,Very Low,Very Low,Low,...,0.900,5,19,Very High,8.047577e+05,13185.814910,NaN,1,1,1.0
1,2,402048.774493,4.385197e+06,Yes,Very High,Very Low,Low,Low,Very Low,Low,...,0.900,5,19,Very High,4.097596e+06,43435.655597,NaN,2,2,1.0
2,3,402298.774493,4.385197e+06,Yes,Very High,Very Low,Low,Very Low,Very Low,Low,...,0.900,2,16,Very High,6.692398e+02,261.964505,NaN,1,1,2.0
3,4,402798.774493,4.385197e+06,Yes,High,Very Low,Low,Low,Very Low,Low,...,0.000,0,13,Medium,2.271303e+02,102.399876,NaN,2,2,2.0
4,5,403048.774493,4.385197e+06,Yes,Very High,Very Low,Low,Low,Very Low,Low,...,0.900,5,19,Very High,1.112810e+07,88968.248809,1.0,1,2,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14323,14324,423798.774493,4.196947e+06,No,Very High,Very High,Very High,High,Moderate,Very Low,...,0.900,2,7,Very Low,4.518002e+02,178.204652,2.0,3,3,NaN
14324,14325,424048.774493,4.196947e+06,No,Very High,Very High,Very High,High,Moderate,Very Low,...,0.900,2,9,Very Low,6.947082e+03,373.812946,2.0,3,3,NaN
14325,14326,421798.774493,4.196697e+06,No,Very High,Very High,Very High,High,Moderate,Low,...,0.001,3,8,Very Low,3.583933e+02,98.070710,2.0,3,3,NaN
14326,14327,422298.774493,4.196697e+06,No,Very High,Very High,Very High,High,Moderate,Low,...,0.900,3,8,Very Low,2.976028e+03,409.458950,2.0,3,3,NaN
14327,14328,422548.774493,4.196697e+06,No,Very High,Very High,Very High,High,Moderate,Low,...,0.900,3,10,Low,4.670595e+03,602.029343,2.0,3,3,NaN

Viewing the original shape before modifying

In [10]:
merged.shape

(14328, 48)

In [11]:
merged.columns

Index(['OBJECTID', 'x', 'y', 'Sheltered_Coastline', 'Geomorphology_Hazard',
       'Elevation_Hazard', 'Sea_Level_Rise_Hazard', 'Wave_Hazard',
       'storm_surge_hazard', 'Erosion_Rate_Hazard', 'Forest_Present',
       'Marsh_Present', 'Dune_Present', 'Oyster_Reef_Present',
       'Underwater_Grass_Present', 'Hazard_with_Habitats',
       'Hazard_without_Habitats', 'Hazard_Reduction_by_Habitats',
       'Community_Flood_Risk_Max', 'Community_Flood_Risk_Nearest',
       'Shoreline_Priority_Area', 'County', 'EI_wHAB', 'EI_woHAB_x',
       'hab_role', 'NearRiskD', 'Latitude', 'Longitude',
       'PercentBufferOccupied', 'HabScore', 'PercentRemaining2100',
       'PercentBufferRemain', 'PersistScore', 'AreaScore', 'PDI', 'SVI',
       'PeopleScore', 'EI_woHAB_y', 'Probability', 'HazScore', 'TotalScore',
       'Overall_Rating', 'Shape__Area', 'Shape__Length',
       'Hazard_Reduction_by_Habitats_Numeric', 'Hazard_with_Habitats_Numeric',
       'Hazard_without_Habitats_Numeric', 'Community_Flood_Risk_Max_Numeric'],
      dtype='object')

Checking for what columns have null values, and how many.

In [19]:
merged.isnull().sum()

OBJECTID                                   0
x                                          0
y                                          0
Sheltered_Coastline                        0
Geomorphology_Hazard                       0
Elevation_Hazard                           0
Sea_Level_Rise_Hazard                      0
Wave_Hazard                                0
storm_surge_hazard                         0
Erosion_Rate_Hazard                        0
Forest_Present                             0
Marsh_Present                              0
Dune_Present                               0
Oyster_Reef_Present                        0
Underwater_Grass_Present                   0
Hazard_with_Habitats                       0
Hazard_without_Habitats                    0
Hazard_Reduction_by_Habitats             711
Community_Flood_Risk_Max                2445
Community_Flood_Risk_Nearest            2445
Shoreline_Priority_Area                 5478
County                                     0
EI_wHAB                                    0
EI_woHAB_x                                 0
hab_role                                   0
NearRiskD                                  0
Latitude                                   0
Longitude                                  0
PercentBufferOccupied                      0
HabScore                                   0
PercentRemaining2100                       0
PercentBufferRemain                        0
PersistScore                               0
AreaScore                                  0
PDI                                        0
SVI                                        0
PeopleScore                                0
EI_woHAB_y                                 0
Probability                                0
HazScore                                   0
TotalScore                                 0
Overall_Rating                             0
Shape__Area                                0
Shape__Length                              0
Hazard_Reduction_by_Habitats_Numeric     711
Hazard_with_Habitats_Numeric               0
Hazard_without_Habitats_Numeric            0
Community_Flood_Risk_Max_Numeric        2445
dtype: int64

I saw that my Shoreline_Priority_Area variable had many missing values. If I removed all the rows where this variable was missing, I would lose close to half of my data. Because of this, I decided to remove the column. My other variables that has missing values also had pretty large amounts of missing data, but not enough that I wouldn't resort to cutting them out completely.

In [27]:
#Used built in Gemini

print(f"Merged Data Original Shape {merged.shape}")


if 'Shoreline_Priority_Area' in merged.columns:
    merged = merged.drop(columns=['Shoreline_Priority_Area'])
    print(f"Shape after dropping 'Shoreline_Priority_Area': {merged.shape}")
else:
    print("'Shoreline_Priority_Area' column not found.")


remaining_nan_cols = merged.columns[merged.isnull().any()].tolist()

if remaining_nan_cols:
    print(f"Remaining columns with NaN values: {remaining_nan_cols}")
    print(f"Shape before dropping rows with NaNs in specific columns: {merged.shape}")
    merged = merged.dropna(subset=remaining_nan_cols)
    print(f"Shape after dropping rows with NaNs in specific columns: {merged.shape}")
else:
    print("No remaining columns with NaN values after dropping 'Shoreline_Priority_Area'.")


display(merged.head())


print("\nMissing values after cleanup:")
display(merged.isnull().sum()[merged.isnull().sum() > 0])

Merged Data Original Shape (11280, 47)
'Shoreline_Priority_Area' column not found.
No remaining columns with NaN values after dropping 'Shoreline_Priority_Area'.

,OBJECTID,x,y,Sheltered_Coastline,Geomorphology_Hazard,Elevation_Hazard,Sea_Level_Rise_Hazard,Wave_Hazard,storm_surge_hazard,Erosion_Rate_Hazard,...,Probability,HazScore,TotalScore,Overall_Rating,Shape__Area,Shape__Length,Hazard_Reduction_by_Habitats_Numeric,Hazard_with_Habitats_Numeric,Hazard_without_Habitats_Numeric,Community_Flood_Risk_Max_Numeric
4,5,403048.774493,4.385197e+06,Yes,Very High,Very Low,Low,Low,Very Low,Low,...,0.9,5,19,Very High,1.112810e+07,88968.248809,1.0,1,2,2.0
5,6,403298.774493,4.385197e+06,Yes,High,Very Low,Low,Low,Very Low,Low,...,0.9,5,13,Medium,1.637441e+04,948.846249,1.0,1,2,2.0
6,7,403548.774493,4.385197e+06,Yes,Moderate,Very Low,Low,Low,Very Low,Very Low,...,0.9,5,14,High,1.845201e+02,84.598824,1.0,1,1,2.0
10,11,403548.774493,4.384947e+06,Yes,Moderate,Very Low,Low,Low,Very Low,Very Low,...,0.9,2,15,High,5.347214e+02,168.860329,1.0,1,1,2.0
15,16,403048.774493,4.384197e+06,Yes,Low,Very Low,Low,Low,Very Low,Low,...,0.9,5,17,Very High,3.727461e+03,359.185303,1.0,1,1,2.0

Missing values after cleanup:

Series([], dtype: int64)

Viewing the final shape of my dataset

In [22]:
merged.shape

(11280, 47)